### ISSUE TITLE
[Windows System]the path file cannot be found（It is recommended to run this code under linux system）

### ISSUE THREAD

**Issue by wrs-code** [guanyingc/SDPS-Net#20]
Hello, your code is very well written, but on windows I tried to implement one stage of network training with the following code.

[CUDA_VISIBLE_DEVICES=0 python main_stage1.py --in_img_num 32]

The following error occurred.

Traceback (most recent call last):

  File "E:\SDPS-Net-master\main_stage1.py", line 36, in <module>
    main(args)
  File "E:\SDPS-Net-master\main_stage1.py", line 25, in main
    train_utils.train(args, train_loader, model, criterion, optimizer, log, epoch, recorder)
  File "E:\SDPS-Net-master\train_stage1.py", line 9, in train
    for i, sample in enumerate(loader):
  File "D:\anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "D:\anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\anaconda\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda\lib\site-packages\torch\utils\data\dataset.py", line 416, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "E:\SDPS-Net-master\datasets\UPS_Synth_Dataset.py", line 36, in __getitem__
    normal_path, img_list, dirs = self._getInputPath(index)
  File "E:\SDPS-Net-master\datasets\UPS_Synth_Dataset.py", line 25, in _getInputPath
    img_list    = util.readList(os.path.join(img_dir, '%s_%s.txt' % (shape, mtrl)))
  File "E:\SDPS-Net-master\datasets\util.py", line 17, in readList
    with open(list_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/datasets/PS_Sculpture_Dataset\\Images\\two-wrestlers-in-combat-repost_Two_wre
stlersincombat_s-0.16_x-010_y-120_024/green-metallic-paint2\\two-wrestlers-in-combat-repost_Two_wrestlersincombat_s-0.16_x-010_y-120_024_green-metallic-paint2.txt'

I think I have unpacked the two PS datasets and put them into data/datasets, but I can't start training, I am a newbie to python, I have checked a lot of information and still can't figure out this error, if you can reply then I would be very grateful.

**Comment by wrs-code** [comment]
By the way I was able to successfully test on the DiLiGenT dataset

**Comment by guanyingc** [comment]
Hi, the path name seems strange "data/datasets/PS_Sculpture_Dataset\Images\two-wrestlers-in-combat-repost_Two_wre
stlersincombat_s-0.16_x-010_y-120_024/green-metallic-paint2\two-wrestlers-in-combat-repost_Two_wrestlersincombat_s-0.16_x-010_y-120_024_green-metallic-paint2.txt", as it contains '/' and '\\'. 

I haven't tested with Windows, but I think you might need to change the code that generates the path name. 

This problem is similar to https://github.com/guanyingc/SDPS-Net/issues/4.

**Comment by girigiri2233** [comment]
Thank you for your reply, I tried to change the path code, but it still reports an error, the following is the error code.

Traceback (most recent call last):
  File "D:\SDPS-Net\main_stage1.py", line 36, in <module>
    main(args)
  File "D:\SDPS-Net\main_stage1.py", line 25, in main
    train_utils.train(args, train_loader, model, criterion, optimizer, log, epoch, recorder)
  File "D:\SDPS-Net\train_stage1.py", line 9, in train
    for i, sample in enumerate(loader):
  File "D:\anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "D:\anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\anaconda\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda\lib\site-packages\torch\utils\data\dataset.py", line 416, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "D:\SDPS-Net\datasets\UPS_Synth_Dataset.py", line 47, in __getitem__
    normal_path, img_list, dirs = self._getInputPath(index)
  File "D:\SDPS-Net\datasets\UPS_Synth_Dataset.py", line 36, in _getInputPath
    img_list = util.readList(img_list)
  File "D:\SDPS-Net\datasets\util.py", line 17, in readList
    with open(list_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\data\\datasets\\PS_Sculpture_Dataset\\Images\\two-wrestlers-in-combat-repost_Two_wrestlersincombat_s-0.16_x-000_y-090_014\\fruitwood-241\\two-wrestlers-in-combat-repost_Two_wrestlersincombat_s-0.16_x-000_y-090_014_fruitwood-241.txt'

I feel very strange, I have this file in windows explorer but still can't access the path，Even though I transformed / all into / /

**Comment by wrs-code** [comment]
> Hi, the path name seems strange "data/datasets/PS_Sculpture_Dataset\Images\two-wrestlers-in-combat-repost_Two_wre stlersincombat_s-0.16_x-010_y-120_024/green-metallic-paint2\two-wrestlers-in-combat-repost_Two_wrestlersincombat_s-0.16_x-010_y-120_024_green-metallic-paint2.txt", as it contains '/' and '\'.
> 
> I haven't tested with Windows, but I think you might need to change the code that generates the path name.
> 
> This problem is similar to #4.

Hi Prof. Chen, I tried to run your code using pycharm with cmd on windows system and when I run the training with no error in the file path I always fail to find the txt file path. I have now switched to linux and tested pycharm and terminal on linux and both are able to run your training program.

So I highly recommend to run this program on linux system, not to run this code on window system or this window's hard disk.

**Comment by guanyingc** [comment]
Thanks for the suggestion.
