### ISSUE TITLE
cannot import name 'PILLOW_VERSION' from PIL

### ISSUE THREAD

**Issue by vinayak-pathak** [guanyingc/SDPS-Net#6]
Hi Authors,
I am getting following issue while testing the model using following code.
CUDA_VISIBLE_DEVICES=1 python eval/run_stage2.py --retrain data/models/LCNet_CVPR2019.pth.tar --retrain_s2 data/models/NENet_CVPR2019.pth.tar

Issue:CUDA_
Traceback (most recent call last):
  File "eval/run_stage2.py", line 7, in <module>
    from utils    import logger, recorders
  File "./utils/logger.py", line 4, in <module>
    import torchvision.utils as vutils
  File "/home/vinayak/miniconda3/envs/py3.7/lib/python3.7/site-packages/torchvision/__init__.py", line 2, in <module>
    from torchvision import datasets
  File "/home/vinayak/miniconda3/envs/py3.7/lib/python3.7/site-packages/torchvision/datasets/__init__.py", line 9, in <module>
    from .fakedata import FakeData
  File "/home/vinayak/miniconda3/envs/py3.7/lib/python3.7/site-packages/torchvision/datasets/fakedata.py", line 3, in <module>
    from .. import transforms
  File "/home/vinayak/miniconda3/envs/py3.7/lib/python3.7/site-packages/torchvision/transforms/__init__.py", line 1, in <module>
    from .transforms import *
  File "/home/vinayak/miniconda3/envs/py3.7/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 17, in <module>
    from . import functional as F
  File "/home/vinayak/miniconda3/envs/py3.7/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 5, in <module>
    from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/home/vinayak/miniconda3/envs/py3.7/lib/python3.7/site-packages/PIL/__init__.py)

**Comment by vinayak-pathak** [comment]
Please help!

**Comment by guanyingc** [comment]
Hi, this might be caused by that you haven't installed the pillow library. Could you try `conda install pillow` first? If this does not work out, you may search this error online to solve it, as this is not a bug of the provided code. Thanks.

**Comment by vinayak-pathak** [comment]
Hi, the issue was resolved by downgrading the PILLOW from 7.0.0. to 6.2.0, Pls refer to [https://github.com/pytorch/vision/issues/1712]  for more details to resolve this issue.
Thanks
